In [1]:
import sqlite3
import pandas as pd

# Create a database connection
conn = sqlite3.connect('practice.db')
print("Database connected successfully!")

Database connected successfully!

In [2]:
df = pd.read_csv('C:/pd/superstore.csv', encoding='latin1')
df.to_sql('superstore', conn, if_exists='replace', index=False)

print("Data loaded into database successfully!")
print(f"Rows loaded: {len(df)}")

Data loaded into database successfully!
Rows loaded: 9994

In [19]:
query = """
SELECT *
FROM superstore
LIMIT 5
"""
result = pd.read_sql_query(query, conn)
result

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [6]:
query = """
SELECT Region, Sales, Profit
FROM Superstore
LIMIT 10
"""
result = pd.read_sql_query(query, conn)
result

  Region     Sales    Profit
0  South  261.9600   41.9136
1  South  731.9400  219.5820
2   West   14.6200    6.8714
3  South  957.5775 -383.0310
4  South   22.3680    2.5164
5   West   48.8600   14.1694
6   West    7.2800    1.9656
7   West  907.1520   90.7152
8   West   18.5040    5.7825
9   West  114.9000   34.4700

In [5]:
query = """
SELECT Region, Sales, Profit
FROM Superstore
WHERE Region = 'West'
LIMIT 10
"""
result = pd.read_sql_query(query, conn)
result

  Region     Sales    Profit
0   West    14.620    6.8714
1   West    48.860   14.1694
2   West     7.280    1.9656
3   West   907.152   90.7152
4   West    18.504    5.7825
5   West   114.900   34.4700
6   West  1706.184   85.3092
7   West   911.424   68.3568
8   West   407.976  132.5922
9   West    55.500    9.9900

In [4]:
query = """
SELECT COUNT(*)  AS total_rows FROM superstore
"""
result = pd.read_sql_query(query, conn)
result

   total_rows
0        9994

In [8]:
#region wise sales
query = """
SELECT Region, SUM(Sales) AS total_sales
FROM superstore
GROUP BY Region
"""
result = pd.read_sql_query(query, conn)
result

    Region  total_sales
0  Central  501239.8908
1     East  678781.2400
2    South  391721.9050
3     West  725457.8245

In [11]:
#AVG profit
query = """
SELECT Category, AVG(Profit) AS AVG_PROFIT
FROM superstore
GROUP BY Category
"""

result = pd.read_sql_query(query, conn)
result

          Category  AVG_PROFIT
0        Furniture    8.699327
1  Office Supplies   20.327050
2       Technology   78.752002

In [20]:
#total sales

query = """
SELECT "Customer Name", SUM(Sales) AS total_sales
FROM superstore
GROUP BY "Customer Name" 
ORDER BY total_sales DESC
LIMIT 5;
"""

result = pd.read_sql_query(query, conn)
result

   Customer Name  total_sales
0    Sean Miller    25043.050
1   Tamara Chand    19052.218
2   Raymond Buch    15117.339
3   Tom Ashbrook    14595.620
4  Adrian Barton    14473.571

In [25]:
#Total profit by category and region is west
query = """
SELECT Category, SUM(Profit) AS TOTAL_PROFIT
FROM superstore
WHERE Region = 'West'
GROUP BY Category
ORDER BY TOTAL_PROFIT DESC
"""

result = pd.read_sql_query(query, conn)
result

          Category  TOTAL_PROFIT
0  Office Supplies    52609.8490
1       Technology    44303.6496
2        Furniture    11504.9503