In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('practice.db')

# Create customers table
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4, 5],
    'name': ['Shruti', 'Raj', 'Priya', 'Arjun', 'Meera'],
    'city': ['Surat', 'Mumbai', 'Delhi', 'Pune', 'Ahmedabad']
})

# Create orders table
orders = pd.DataFrame({
    'order_id': [101, 102, 103, 104],
    'customer_id': [1, 2, 1, 6],
    'amount': [500, 1200, 800, 300]
})

# Load into database
customers.to_sql('customers', conn, if_exists='replace',index='False')
orders.to_sql('orders', conn, if_exists='replace', index='False')

print("Tables created successfully!")
print("\nCustomers table:")
print(customers)
print("\nOrders table:")
print(orders)

Tables created successfully!

Customers table:
   customer_id    name       city
0            1  Shruti      Surat
1            2     Raj     Mumbai
2            3   Priya      Delhi
3            4   Arjun       Pune
4            5   Meera  Ahmedabad

Orders table:
   order_id  customer_id  amount
0       101            1     500
1       102            2    1200
2       103            1     800
3       104            6     300

In [11]:
query = """
SELECT customers.name, customers.city, orders.order_id, orders.amount
FROM "customers"
INNER JOIN "orders" ON "customers".customer_id = "orders".customer_id
"""

result = pd.read_sql_query(query, conn)
result

     name    city  order_id  amount
0  Shruti   Surat       101     500
1  Shruti   Surat       103     800
2     Raj  Mumbai       102    1200

In [12]:
query = """
SELECT customers.name, customers.city, orders.order_id, orders.amount
FROM "customers"
LEFT JOIN "orders" ON "customers".customer_id = "orders".customer_id
"""

result = pd.read_sql_query(query, conn)
result

     name       city  order_id  amount
0  Shruti      Surat     101.0   500.0
1  Shruti      Surat     103.0   800.0
2     Raj     Mumbai     102.0  1200.0
3   Priya      Delhi       NaN     NaN
4   Arjun       Pune       NaN     NaN
5   Meera  Ahmedabad       NaN     NaN

In [13]:
# Split superstore into two tables
df = pd.read_csv('C:/pd/superstore.csv', encoding='latin1')

# Table 1 — orders info
orders_df = df[['Order ID', 'Customer Name', 'Region', 'Sales', 'Profit']]

# Table 2 — product info  
products_df = df[['Order ID', 'Category', 'Sub-Category', 'Product Name']]

# Load into database
orders_df.to_sql('orders_info', conn, if_exists='replace', index=False)
products_df.to_sql('products_info', conn, if_exists='replace', index=False)

print("Tables created!")
print("Orders table shape:", orders_df.shape)
print("Products table shape:", products_df.shape)

Tables created!
Orders table shape: (9994, 5)
Products table shape: (9994, 4)

In [37]:
query = """
SELECT products_info.Category, SUM(orders_info.Sales) AS total_sales
FROM orders_info
INNER JOIN products_info ON orders_info."Order ID" = products_info."Order ID"
GROUP BY Category
ORDER BY total_sales DESC
"""
#here i have found duplicate join problem
result = pd.read_sql_query(query, conn)
result

          Category   total_sales
0  Office Supplies  3.596313e+06
1       Technology  1.762552e+06
2        Furniture  1.755220e+06

In [43]:
query = """
SELECT COUNT(*) FROM products_info
"""
result = pd.read_sql_query(query, conn)
result

   COUNT(*)
0      9994